### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by kabilsharma** [graphhopper/graphhopper-navigation-android#6]
Trying to make a navigation app

using this to render custom vector tiles

https://github.com/maplibre/maplibre-gl-native

Now when we use mapbox navigation android version 22 (open source)

https://github.com/mapbox/mapbox-navigation-android/releases?after=testapp-3

We are facing following errors. 

The mapbox navigation sdk version .22 is not compatible with map sdk 8.2.1 (maplibre open source) and if we downgrade map sdk to 6.6.2 it asks for access token to render tiles.

As maps are already rendering best open source option to run navigation is grasshopper routing engine.

Kindly suggest (grasshopper navigation sdk giving error 401)

Our team is currently working on creating flow charts and documentation on how navigation code flow works. we will share once they are ready.

Thanks a lot karussell for your wonderful efforts towards navigation sdk. You have been fighting all along to keeping this sdk open source as much as you can. 

Kindly suggest which version we should start our development.

**Comment by boldtrn** [comment]
One of the first things that should be done on this repository IMHO is to update the maps library to use the latest maplibre maps sdk - contributions are welcome ;).

**Comment by karussell** [comment]
See the comments in #8.
