### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jamiesonbates** [graphhopper/graphhopper-navigation-android#7]
### Steps to trigger behavior

 1. Add `implementation 'com.graphhopper.navigation:navigation-android:0.1.0'` to android/app/build.gradle
 2. Run build

### Expected behavior

Successful installation of this library.

### Actual behavior

It is unclear what the installation issue is. I also attempted to replicate installation from the [example](https://github.com/graphhopper/graphhopper-navigation-example), with no success.

![Screen Shot 2021-04-23 at 2 51 06 PM](https://user-images.githubusercontent.com/9344645/115933277-676ea280-a443-11eb-8106-639388fe341f.png)

**Comment by SumedhShriram** [comment]
Use this:
implementation 'com.graphhopper:graphhopper-navigation-android-ui:0.1.0-SNAPSHOT'

this implementation worked for me but ran into another issue after that. The repo contains mapbox-android-sdk-6.5 and I'm adding 
 implementation 'org.maplibre.gl:android-sdk:9.4.0' t use the latest maplibre. This is causing issues with duplication and not sure what the solution is.
I've tried excluding the module 'mapbox-android-sdk' but that causes another issue with the xml files.
Lot of interlocked dependencies.

**Comment by karussell** [comment]
> Lot of interlocked dependencies.

It is important to note that currently this repo is not yet compatible with maplibre SDK. See #6
